WebApplication29/Controllers/CostumerController.cs
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using WebApplication29.Models;

namespace WebApplication29.Controllers
{
    public class CostumerController : Controller
    {
        private readonly HomeServicesNewContext _context;
        private IWebHostEnvironment _hostEnvironment;
        private readonly IToastNotification _toastNotification;
        public CostumerController(HomeServicesNewContext context, IWebHostEnvironment hostEnvironment, IToastNotification toastNotification)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            _toastNotification = toastNotification;

        }
        HomeServicesNewContext db = new HomeServicesNewContext();
        public IActionResult Index()
        {
            string id = "id";

            int? employeeid = HttpContext.Session.GetInt32(id);
            ViewBag.id = HttpContext.Session.GetInt32(id);
            if (employeeid==null)
            {
                _toastNotification.AddErrorToastMessage("Login First please");

                return RedirectToAction("Login", "LoginAndSession");
            }
           
            List<UserService> userServices = db.UserServices.ToList();
            List<User> users = db.Users.ToList();
            List<Service> services = db.Services.ToList();
            List<Payment> payments = db.Payments.ToList();
            ViewBag.CountOfUserServices = _context.UserServices.Where(x => x.UserId == employeeid).Count();
            var AllServices = from us in users
                              join usSer in userServices on us.UserId equals usSer.UserId into table1
                              from usSer in table1.ToList()
                              join pay in payments on usSer.UserServiceId equals pay.UserServiceId into table2
                              from pay in table2.ToList()


                              select new joins { users = us, payment = pay, userService = usSer };


            var multable1 = AllServices.Where(x => x.users.UserId== employeeid).Select(x=>x.payment.PaymentAmount).Sum();
            ViewBag.CountOfPayment=multable1;


            var dServices = from usSer in userServices
                              join us in users on usSer.UserId equals us.UserId into table1
                              from us in table1.ToList()
                              join ser in services on usSer.ServiceId equals ser.ServiceId into table2
                              from ser in table2.ToList()

                              select new joins { users = us, services = ser, userService = usSer };




            dServices = dServices.Where(x => x.userService.UserId == employeeid);
            var DoneServices = dServices.Where(x => x.userService.Status == "Done" || x.userService.Status == "done").ToList();

            ViewBag.CountOfDoneServices = DoneServices.Count();
            ViewBag.CountOfTodayServices = _context.UserServices.Where(x => x.UserId == employeeid && x.Date==DateTime.Today).Count();

            var AllUserServices = from ser in services
                              join us in users on ser.UserId equals us.UserId into table1
                              from us in table1.ToList()
                              join usSer in userServices on ser.ServiceId equals usSer.ServiceId into table2
                              from usSer in table2.ToList()


                              select new joins { users = us, services = ser, userService = usSer };
            AllUserServices = AllUserServices.Where(x => x.userService.UserId == employeeid).ToList().OrderBy(x=>x.userService.Date);

            return View(AllUserServices);
        }
        public IActionResult AddReview()
        {
            string id = "id";
            int? employeeid = HttpContext.Session.GetInt32(id);
            ViewBag.id = HttpContext.Session.GetInt32(id);

            List<Service> services = db.Services.ToList();

            List<User> user = db.Users.ToList();

            List<UserService> userServices = db.UserServices.ToList();


            var AllServices = from usSer in userServices
                              join us in user on usSer.UserId equals us.UserId into table1
                              from us in table1.ToList()
                              join ser in services on usSer.ServiceId equals ser.ServiceId into table2
                              from ser in table2.ToList()

                              select new joins { users = us, services = ser, userService = usSer };


            

            AllServices = AllServices.Where(x => x.userService.UserId == employeeid );
           var DoneServices=AllServices.Where(x => x.userService.Status == "Done"||x.userService.Status=="done");

            return View(DoneServices.ToList());
        }

        public IActionResult Checkpayments()
        {
            return View();
        }
        public IActionResult ServicesDetails(int UserServiceId)
        {
           
            List<UserService> userServices = db.UserServices.ToList();
            List<Service> services = db.Services.ToList();
            var AllServices = from usSer in userServices
                              join ser in services on usSer.ServiceId equals ser.ServiceId into table1
                              from ser in table1.ToList()

                              select new joins {  services = ser, userService = usSer };


            ViewBag.UserServiceId = UserServiceId;
            AllServices = AllServices.Where(x=>x.userService.UserServiceId==UserServiceId).ToList();

            return View(AllServices);
        }
        public IActionResult CreateReview(int UserServiceId,double ReviewRange,string ReviewText,Review review)
        {
          review.UserServiceId = UserServiceId;
          review.ReviewRange = ReviewRange;
          review.ReviewText = ReviewText;
            _context.Add(review);

            _context.SaveChangesAsync();



            _toastNotification.AddAlertToastMessage("thank you for the review");
            return RedirectToAction("AddReview");
        }
     
        public IActionResult ChangePassword()
        {
            string id = "id";
            int? employeeid = HttpContext.Session.GetInt32(id);
            ViewBag.id = HttpContext.Session.GetInt32(id);
          
            List<Login> logins = db.Logins.ToList();
            List<User> users = db.Users.ToList();
            var multable = from usr in users
                           join log in logins on usr.LoginId equals log.LoginId into table1
                           from log in table1.ToList()
                           select new joins { users = usr, logins = log };
            multable = multable.Where(x => x.users.UserId == employeeid).ToList();

            var pas = multable.Select(x => x.logins.Password).ToList();
            ViewBag.password = pas.FirstOrDefault();

            ViewBag.FirstName = users.Where(x=>x.UserId==employeeid).Select(x=>x.FirstName).FirstOrDefault();
            ViewBag.LastName = users.Where(x => x.UserId == employeeid).Select(x => x.LastName).FirstOrDefault();
            ViewBag.Gender = users.Where(x => x.UserId == employeeid).Select(x => x.Gender).FirstOrDefault();
            ViewBag.Email = users.Where(x => x.UserId == employeeid).Select(x => x.Email).FirstOrDefault();
            ViewBag.PhoneNumber = users.Where(x => x.UserId == employeeid).Select(x => x.PhoneNumber).FirstOrDefault();
            ViewBag.Adress = users.Where(x => x.UserId == employeeid).Select(x => x.Adress).FirstOrDefault();
            ViewBag.City = users.Where(x => x.UserId == employeeid).Select(x => x.City).FirstOrDefault();
            ViewBag.BirthDate = users.Where(x => x.UserId == employeeid).Select(x => x.BirthDate).FirstOrDefault();
            ViewBag.UserImage = users.Where(x => x.UserId == employeeid).Select(x => x.UserImage).FirstOrDefault();

            return View();
        }
        public IActionResult Profile(string FirstName,string LastName,string Gender,string Email ,string PhoneNumber,string Adress,string City,DateTime BirthDate,string UserImage, IFormFile? ImageFile,User user)
        {
            List<User> users = db.Users.ToList();
            string id = "id";
            int employeeid = (int)HttpContext.Session.GetInt32(id);
            user.LoginId=users.Where(x => x.UserId == employeeid).Select(x => x.LoginId).FirstOrDefault();
            user.FirstName = FirstName;
            user.LastName = LastName;   
            user.Gender = Gender;
            user.Email = Email;
            user.PhoneNumber = PhoneNumber;
            user.Adress = Adress;
            user.City = City;
            user.BirthDate = BirthDate;
            user.UserImage=
            user.UserImage = UserImage;
            if (user.ImageFile != null)
            {
                string wRootPath = _hostEnvironment.WebRootPath;
                string fileName = Guid.NewGuid().ToString() + "_" + user.ImageFile.FileName;
                string path = Path.Combine(wRootPath + "/Image/", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {

                   user.ImageFile.CopyToAsync(fileStream);
                }
                user.UserImage = fileName;
            }
            user.UserId = employeeid;
            _context.Update(user);

            _context.SaveChangesAsync();
            _toastNotification.AddSuccessToastMessage("Update profile Success");
            return RedirectToAction("ChangePassword");
        }
        public IActionResult ChangePasswordBasic(string CurrentPassword, string NewPassword, string ConfirmPssword, Login login)
        {
            string id = "id";
            int? employeeid = HttpContext.Session.GetInt32(id);
            ViewBag.id = HttpContext.Session.GetInt32(id);
            List<Login> logins = db.Logins.ToList();
            List<User> users = db.Users.ToList();

WebApplication29/Views/Costumer/AddReview.cshtml
@model IEnumerable<WebApplication29.Models.joins>

@{

 Layout = "~/Views/Shared/_CustomerLayout.cshtml";
    var countOFEmployees= ViewBag.countOFEmployees ;

    var countOFUsers = ViewBag.countOFUsers; 
       string[] TableHeaders = new string[]{" ","Img","ServiceName"
          ,"Price","Description","Date","Status"
     };

}

             <script src="~/jsfiles/FileSaver.js"></script> @*could be downloaded from https://github.com/eligrey/FileSaver.js/blob/master/src/FileSaver.js*@
<script>
    function fnExcelReport(id, name) {
        var tab_text = '<html xmlns: x="urn:schemas-microsoft-com:office:excel">';
        tab_text = tab_text + '<head><xml><x: ExcelWorkbook><x: ExcelWorksheets><x: ExcelWorksheet>';
        tab_text = tab_text + '<x: Name>Test Sheet</x: Name>';
        tab_text = tab_text + '<x: WorksheetOptions><x: Panes></x: Panes></x: WorksheetOptions ></x: ExcelWorksheet > ';
        tab_text = tab_text + '</x:ExcelWorksheets></x:ExcelWorkbook></xml></head><body>';
        tab_text = tab_text + "<table border='1px' style='color:black'>";

        var exportTable = $('#' + id).clone();
        exportTable.find('th').last().remove();
        exportTable.find('input').each(function (index, elem) { $(elem).remove(); });
        exportTable.find('a').each(function (index, elem) { $(elem).remove(); });

        tab_text = tab_text + exportTable.html();

        var fileName = "category" + '.xls';
        //Save the file
        var blob = new Blob([tab_text], { type: "application/vnd.ms-excel;charset=utf-8" })
        window.saveAs(blob, fileName);

    }
</script>
 
    

                
      <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Services Status </h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                                            @{
                    foreach (var head in TableHeaders)
                    {
                        <th>
                            @head
                        </th>
                    }
                }
                                        </tr>
                                    </thead>
        <tbody>

            @{
                
                 @if (Model != null)
            {
                foreach (var data in Model)
             
                {
                    
                     var index = Model.ToList().IndexOf(data)+1;
                                    <tr>
                                        <td>@index </td>
                    <td>  <img src="~/Image/@data.services.UserImage" asp-append-version="true" width="150px" height="100" style="border-radius:50%;" /></td>
                     
                        <td>@data.services.ServiceName </td>
                        <td>@data.services.Price </td>
                        <td>@data.services.Description</td>
                         <td>@data.userService.Date </td>
                          <td>@data.userService.Status </td>
                          
                    
                          <td id="f">
                            @using (Html.BeginForm("ServicesDetails", "Costumer", new { UserServiceId = @data.userService.UserServiceId }, FormMethod.Post))
                            {
                                <button class="btn btn-primary">Add Review </button>
                            }
                        </td>

                    </tr>


                }
            }
            }
        </tbody>
                  </table>
                        </div>
                        </div>
                    </div>

          
            <button class="btn btn-primary" onclick="javascript:fnExcelReport('dataTable', 'data')">Export To Excel</button>
      <input style="margin-left:5px;" type="button" onclick="generate()" class="btn btn-primary"  value="Export To PDF" />


<script src="script.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.6/jspdf.plugin.autotable.min.js"></script>

<script>
    function generate() {
        var doc = new jsPDF("p", "mm", "a2");
        var htmlstring = '';
        var tempVarToCheckPageHeight = 0;
        var pageHeight = 0;
        pageHeight = doc.internal.pageSize.height;
        
var width = doc.internal.pageSize.getWidth();
        specialElementHandlers = {
            // element with id of "bypass" - jQuery style selector
            '#bypassme': function (element, renderer) {
                // true = "handled elsewhere, bypass text extraction"
                return true
            }
        };
        margins = {
            top: 200,
            bottom: 60,
            left: 100,
            right: 100,
            width: 700,
           
        };
      
        var y = 20;
        doc.setLineWidth(3);

        doc.autoTable({
            html: '#dataTable',

        })
        doc.save('Category.pdf');
    }

</script>

WebApplication29/Views/Costumer/ChangePassword.cshtml
@{

    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
     var FirstName=ViewBag.FirstName;
     var LastName=ViewBag.LastName;
     var Gender=ViewBag.Gender;
     var Email=ViewBag.Email;
     var PhoneNumber=ViewBag.PhoneNumber;
     var Adress=ViewBag.Adress;
     var City=ViewBag.City;
     var BirthDate=ViewBag.BirthDate;
     var UserImage=ViewBag.UserImage ;


}

    <meta name="viewport" content="width=device-width, initial-scale=1">
	



<div class="container light-style flex-grow-1 container-p-y">

    <h4 class="font-weight-bold py-3 mb-4">
      Account settings
    </h4>

    <div class="card overflow-hidden">
      <div class="row no-gutters row-bordered row-border-light">
        <div class="col-md-3 pt-0">
          <div class="list-group list-group-flush account-settings-links">
            <a class="list-group-item list-group-item-action active" data-toggle="list" href="#account-general">General</a>
            <a class="list-group-item list-group-item-action" data-toggle="list" href="#account-change-password">Change password</a>
            <a class="list-group-item list-group-item-action" data-toggle="list" href="#account-info">Info</a>
             </div>
        </div>
        <div class="col-md-9">
          <div class="tab-content">
     
            <div class="tab-pane fade active show" id="account-general">
                         <form asp-action="Profile" enctype="multipart/form-data">
              <div class="card-body media align-items-center">
<img src="~/Image/@UserImage" asp-append-version="true" width="150px" height="100" style="border-radius:50%;" />
                <div class="media-body ml-4">
                   <div class="input-group">
                     <label class="label">ImageFile</label>
                     <input class="input--style-4" type="file" name="ImageFile" accept="image/*"  />
                      </div>

                  <div class="text-light small mt-1">Allowed JPG, GIF or PNG. Max size of 800K</div>
                </div>
              </div>
              <hr class="border-light m-0">

              <div class="card-body">

    <div class="form-group" style="margin-right:15px;">
                  <label class="form-label" >First name</label>
                  <input type="text" readonly name="FirstName" class="form-control mb-1" value="@FirstName"></div>
              <div class="form-group" style="margin-right:15px;">
                  <label class="form-label" >LastName</label>
                  <input type="text" name="LastName" readonly class="form-control" value="@LastName">
                
       
              </div>
                       <input hidden name="UserImage" value="@UserImage">
                <div class="form-group"style="margin-right:15px;">
                  <label class="form-label" >Gender</label>
                  <input type="text"readonly name="Gender" class="form-control mb-1" value="@Gender">
                 
                </div>
                <div class="form-group" style="margin-right:15px;">
                  <label class="form-label" >Email</label>
                  <input type="email" name="Email" class="form-control" value="@Email">
                </div>
             
                <div class="form-group" style="margin-right:15px;">
                  <label class="form-label" >PhoneNumber</label>
                  <input type="text" pattern="[7]{1}[0-9]{9}" title="Phone number start with 7 and remaing 9 digit with 0-9"  name="PhoneNumber" class="form-control mb-1" value="@PhoneNumber">
                 
                </div>
                <div class="form-group" style="margin-right:15px;">
                  <label class="form-label" >BirthDate</label>
                  <input type="datetime" name="BirthDate" readonly class="form-control" value="@BirthDate">
                </div>
              
                <div class="form-group" style="margin-right:15px;">
                  <label class="form-label" >Address</label>
                  <input type="text" pattern="^[a-zA-Z]{3,15}$" title="Address may only contain letters "  name="Adress" class="form-control mb-1" value="@Adress">
                 
                </div>
                <div class="form-group" style="margin-right:15px;">
                  <label class="form-label" >City</label>
                  <input type="text" name="City" pattern="^[a-zA-Z]{3,15}$" title="City may only contain letters "  class="form-control" value="@City">
                </div>
              
                   <button type="submit" class="btn btn-primary">Save changes</button>
                     </form>
            </div>
            </div>
            
               
          
            <div class="tab-pane fade" id="account-change-password">
             
              <div class="card-body pb-2">
                     <form asp-action="ChangePasswordBasic">
                <div class="form-group">
                  <label class="form-label">Current password</label>
                  <input type="password"  class="form-control" name="CurrentPassword">
                </div>

                <div class="form-group">
                  <label class="form-label">New password</label>
                  <input type="password" class="form-control"  pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}" title="at least one number and one uppercase and lowercase letter, and at least 6 or more characters" name="NewPassword" >
                </div>

                <div class="form-group">
                  <label class="form-label">Repeat new password</label>
                  <input type="password" class="form-control"  pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}" title="at least one number and one uppercase and lowercase letter, and at least 6 or more characters" name="ConfirmPssword">
                </div>

       
                    <button type="submit" class="btn btn-primary">Save changes</button>
              </form>
                     </div>
            </div>
            <div class="tab-pane fade" id="account-info">
      
                    <div class="card-body pb-2">
                         <form asp-action="UserNameUpdate">
                <div class="form-group">
                  <label class="form-label">Current UserName</label>
                  <input type="text"  name="CurrentUserName" class="form-control" >
                </div>
                <div class="form-group">
                  <label class="form-label">New UserName</label>
                  <input type="text" name="NewUserName" pattern="^[a-zA-Z][a-zA-Z0-9-_.]{5,12}$" title="alphanumeric 6 to 12 chars"   class="form-control" >
                </div>
                
         
                                 <button type="submit" class="btn btn-primary">Save changes</button>
                </form>
                     </div>
              </div>
              <hr class="border-light m-0">
              <div class="card-body pb-2">
               
              </div>
      
            </div>

              </div>
            </div>
          </div>

   




<style type="text/css">
body{
    background: #f5f5f5;

}

.ui-w-80 {
    width: 80px !important;
    height: auto;
}

.btn-default {
    border-color: rgba(24,28,33,0.1);
    background: rgba(0,0,0,0);
    color: #4E5155;
}

label.btn {
    margin-bottom: 0;
}

.btn-outline-primary {
    border-color: #26B4FF;
    background: transparent;
    color: #26B4FF;
}

.btn {
    cursor: pointer;
}

.text-light {
    color: #babbbc !important;
}

.btn-facebook {
    border-color: rgba(0,0,0,0);
    background: #3B5998;
    color: #fff;
}

.btn-instagram {
    border-color: rgba(0,0,0,0);
    background: #000;
    color: #fff;
}

.card {
    background-clip: padding-box;
    box-shadow: 0 1px 4px rgba(24,28,33,0.012);
}

.row-bordered {
    overflow: hidden;
}

.account-settings-fileinput {
    position: absolute;
    visibility: hidden;
    width: 1px;
    height: 1px;
    opacity: 0;
}
.account-settings-links .list-group-item.active {
    font-weight: bold !important;
}
html:not(.dark-style) .account-settings-links .list-group-item.active {
    background: transparent !important;
}
.account-settings-multiselect ~ .select2-container {
    width: 100% !important;
}
.light-style .account-settings-links .list-group-item {
    padding: 0.85rem 1.5rem;
    border-color: rgba(24, 28, 33, 0.03) !important;
}
.light-style .account-settings-links .list-group-item.active {
    color: #4e5155 !important;
}
.material-style .account-settings-links .list-group-item {
    padding: 0.85rem 1.5rem;
    border-color: rgba(24, 28, 33, 0.03) !important;
}
.material-style .account-settings-links .list-group-item.active {
    color: #4e5155 !important;
}
.dark-style .account-settings-links .list-group-item {
    padding: 0.85rem 1.5rem;
    border-color: rgba(255, 255, 255, 0.03) !important;
}
.dark-style .account-settings-links .list-group-item.active {
    color: #fff !important;
}
.light-style .account-settings-links .list-group-item.active {
    color: #4E5155 !important;
}
.light-style .account-settings-links .list-group-item {
    padding: 0.85rem 1.5rem;
    border-color: rgba(24,28,33,0.03) !important;
}



</style>

<script type="text/javascript">

</script>

WebApplication29/Views/Costumer/ServicesDetails.cshtml
@model IEnumerable<WebApplication29.Models.joins>

@{
           Layout = "~/Views/Shared/_CustomerLayout.cshtml";

		   var UserServicesId= ViewBag.UserServiceId;

}
	<section id="content">
		<div class="container content">	
<div class="row">
			<div class="col-md-12">
				<div><h2>Our Quality Service</h2>We are happy to know your review and expenriance with us .</div>
				<br>
			</div>
		</div>		
        <!-- Service Blcoks -->

     <section id="content">
	
	<div id="placeholderhere">
	<div class="container">
			<div class="row">
				 <div class="skill-home" style="width: 285px; background-color: #ffc02adb;border-radius: 10px;"> <div class="skill-home-solid clearfix" style="display: flex; flex-wrap: wrap; flex-direction: row; align-content: flex-start;">
	
							  @{
                
                 @if (Model != null)
            {
			                @foreach (var user in Model)
    {
		
	
			<div class="col-md-3 "  >
				 		<div class="box" style="margin-top:50px;" > 
	<img src="~/Image/@user.services.UserImage" asp-append-version="true"style="width:260px;height:152.125px" style="border-radius:50%;" />
		<div class="box-area"  style="color: black; margin-top: 10px;width: 260px;margin-bottom: 20px;">
		<h4>@user.services.ServiceName</h4> 
			<p>@user.services.Description</p> 
		<h4>price:@user.services.Price jd</h4>
			<h4>status:@user.userService.Status </h4>
				<h6>date:@user.userService.Date </h6>
		
						
</div></div>
		</div>		 	
    }}}</div>
		</div></div>
		
		</div></div></section>
		</div>
	 

	<div style="margin-left: 30px;margin-top: 30px;">
		<form asp-action="CreateReview">

	<h3>Your Review</h3>
  <div class="rate">
    <input type="radio" id="star5" name="ReviewRange" value="5" />
    <label for="star5" title="text">5 stars</label>
    <input type="radio" id="star4" name="ReviewRange" value="4" />
    <label for="star4" title="text">4 stars</label>
    <input type="radio" id="star3" name="ReviewRange" value="3" />
    <label for="star3" title="text">3 stars</label>
    <input type="radio" id="star2" name="ReviewRange" value="2" />
    <label for="star2" title="text">2 stars</label>
    <input type="radio" id="star1" name="ReviewRange" value="1" />
    <label for="star1" title="text">1 star</label>
  </div>

<input type="hidden" name="UserServiceId" id="UserServiceId" class="form-control" value="@UserServicesId"  readonly="readonly" placeholder="UserServiceId" required>

					<input  name="ReviewText" id="ReviewText" class="form-control" placeholder="ReviewText"  type="text"  >
					    	<button type="submit" class="btn btn-primary " style="border-radius:15px; border:5px;margin-top: 20px;">Submit</button>
                    
				
								</form></div>
	<style>
	*{
    margin: 0;
    padding: 0;
}
.rate {
    float: left;
    height: 46px;
    padding: 0 10px;
}
.rate:not(:checked) > input {
    position:absolute;
    top:-9999px;
}
.rate:not(:checked) > label {
    float:right;
    width:1em;
    overflow:hidden;
    white-space:nowrap;
    cursor:pointer;
    font-size:30px;
    color:#ccc;
}
.rate:not(:checked) > label:before {
    content: '★ ';
}
.rate > input:checked ~ label {
    color: #ffc700;    
}
.rate:not(:checked) > label:hover,
.rate:not(:checked) > label:hover ~ label {
    color: #deb217;  
}
.rate > input:checked + label:hover,
.rate > input:checked + label:hover ~ label,
.rate > input:checked ~ label:hover,
.rate > input:checked ~ label:hover ~ label,
.rate > label:hover ~ input:checked ~ label {
    color: #c59b08;
}

/* Modified from: https://github.com/mukulkant/Star-rating-using-pure-css */</style>